/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/

-- Find total customers by countries
SELECT 
    country,
    COUNT(customer_key) as total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC

-- Find total customers by gender

SELECT 
    gender,
    COUNT (customer_key) as total_customers
FROM gold.dim_customers
GROUP BY gender


-- Find total products by category

SELECT 
    category,
    COUNT (product_name) as total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC 


-- What is the average costs in each category?

SELECT
    category,
    COUNT (product_name) as total_products,
    AVG (cost) AS avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC

-- What is the total revenue generated for each category?

SELECT 
    p.category,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON f.product_key = p.product_key
GROUP BY p.category
ORDER BY total_revenue

-- What is the total revenue generated by each customer?
SELECT 
    c.customer_key,
    CONCAT(c.first_name, ' ', c.last_name) AS name,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON f.customer_key = c.customer_key
GROUP BY 
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY 
    total_revenue DESC;

-- What is the distribution of sold items across countries?

SELECT
    country,
    COUNT(quantity) as total_items_sold
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON f.customer_key = c.customer_key
GROUP BY country
ORDER BY total_items_sold
